CREATE TABLE PHR_AUTH_TRANSACTION(
  id BIGSERIAL PRIMARY KEY NOT NULL,
  auth_transaction_id uuid NOT NULL DEFAULT uuid_generate_v4() UNIQUE NOT NULL,
  health_id_number VARCHAR(17),
  auth_method VARCHAR(20) NOT NULL,
  phr_address VARCHAR(50),
  mobile VARCHAR(10),
  email VARCHAR(320),
  otp VARCHAR(255),
  retry_method VARCHAR(20),
  retry_count INTEGER DEFAULT 0,
  password VARCHAR(255),
  mobile_country_code VARCHAR(8) DEFAULT '+91',
  status VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL,
  health_id_transaction_id VARCHAR(50),
  created_date TIMESTAMP DEFAULT NOW() NOT NULL,
  created_by VARCHAR(50) DEFAULT 'PHR_WEB_APP' NOT NULL,
  updated_date TIMESTAMP DEFAULT NOW() NOT NULL,
  updated_by VARCHAR(50) DEFAULT 'PHR_WEB_APP' NOT NULL
);

CREATE INDEX PHR_AUTH_TRANSACTION_ID_IDX ON PHR_AUTH_TRANSACTION (id);
CREATE INDEX PHR_AUTH_TRANSACTION_ATXNID_IDX ON PHR_AUTH_TRANSACTION (auth_transaction_id);
CREATE INDEX PHR_AUTH_TRANSACTION_HIDXNID_IDX ON PHR_AUTH_TRANSACTION (health_id_transaction_id);